# Generated by Django 5.2.3 on 2025-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='background_color',
            field=models.CharField(default='#fff8b3', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
