# Generated by Django 5.2.3 on 2025-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_background_color_note_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='note',
            name='width',
            field=models.IntegerField(default=160),
        ),
    ]
