# Generated by Django 5.2.3 on 2025-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_board_position_x_board_position_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='emoji',
            field=models.CharField(default='📄', max_length=2),
        ),
    ]
